development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: city_development
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: city_test
  username: postgres
  password: root
